CREATE DATABASE IF NOT EXISTS TaxiPilot
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE TaxiPilot;

CREATE TABLE VehicleLK (
  Id INT NOT NULL AUTO_INCREMENT,
  Make VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Seats INT NOT NULL,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
);

CREATE TABLE VehicleTypesLK (
  Id INT NOT NULL AUTO_INCREMENT,
  Type VARCHAR(20) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
);

CREATE TABLE Driver (
  Id INT NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  LicenseNumber VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  Email VARCHAR(100) NULL,
  Address VARCHAR(255) NULL,
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedBy VARCHAR(50) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE DriverVehicle (
  Id INT NOT NULL AUTO_INCREMENT,
  DriverId INT NOT NULL,
  VehicleId INT NOT NULL,
  VehicleTypes VARCHAR(15) NULL,
  StartDateUsing DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EndDateUsing DATETIME NULL,
  UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  CONSTRAINT FK_DriverVehicle_Driver FOREIGN KEY (DriverId) REFERENCES Driver (Id),
  CONSTRAINT FK_DriverVehicle_VehicleLK FOREIGN KEY (VehicleId) REFERENCES VehicleLK (Id)
);

CREATE TABLE UserLogin (
  Id INT NOT NULL AUTO_INCREMENT,
  UsernameHash VARCHAR(256) NOT NULL,
  PasswordHash VARCHAR(256) NULL,
  UserType VARCHAR(20) NULL,
  EmailHash VARCHAR(256) NULL,
  FirstName VARCHAR(50) NULL,
  LastName VARCHAR(50) NULL,
  PhoneNumber VARCHAR(256) NULL,
  PhoneNumberHash VARCHAR(256) NULL,
  MobileNumberHash VARCHAR(256) NULL,
  DobHash VARCHAR(256) NULL,
  CompanyIdHash VARCHAR(256) NULL,
  HouseNo VARCHAR(256) NULL,
  Street VARCHAR(256) NULL,
  Town VARCHAR(100) NULL,
  County VARCHAR(100) NULL,
  Country VARCHAR(100) NULL,
  PostCode VARCHAR(20) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE KEY UQ_UserLogin_UsernameHash (UsernameHash),
  UNIQUE KEY UQ_UserLogin_EmailHash (EmailHash)
);

CREATE TABLE Employee (
  Id INT NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  EncryptedUserId LONGBLOB NULL,
  EncryptedPassword LONGBLOB NULL,
  Position VARCHAR(100) NULL,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
);

CREATE TABLE SettingLK (
  Id INT NOT NULL AUTO_INCREMENT,
  SettingKey VARCHAR(100) NOT NULL,
  SettingValue TEXT NULL,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
);

CREATE TABLE Ride (
  Id INT NOT NULL AUTO_INCREMENT,
  DriverId INT NOT NULL,
  VehicleId INT NOT NULL,
  CustomerId INT NOT NULL,
  PickupLocation VARCHAR(255) NOT NULL,
  DropoffLocation VARCHAR(255) NOT NULL,
  RideDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FareAmount DECIMAL(10, 2) NOT NULL,
  Distance DECIMAL(10, 2) NULL,
  Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedBy VARCHAR(50) NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_Ride_Driver FOREIGN KEY (DriverId) REFERENCES Driver (Id),
  CONSTRAINT FK_Ride_VehicleLK FOREIGN KEY (VehicleId) REFERENCES VehicleLK (Id),
  CONSTRAINT FK_Ride_UserLogin FOREIGN KEY (CustomerId) REFERENCES UserLogin (Id)
);

CREATE TABLE UserLoginAttempt (
  Id INT NOT NULL AUTO_INCREMENT,
  UserId INT NULL,
  AttemptTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IsSuccessful TINYINT(1) NOT NULL,
  IpAddress VARCHAR(45) NULL,
  Created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserLoginAttempt_UserLogin FOREIGN KEY (UserId) REFERENCES UserLogin (Id) ON DELETE CASCADE
);

CREATE TABLE UserNote (
  Id INT NOT NULL AUTO_INCREMENT,
  RideId INT NULL,
  UserId INT NULL,
  Note TEXT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CreatedBy VARCHAR(50) NOT NULL,
  UpdatedBy VARCHAR(50) NOT NULL,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserNote_Ride FOREIGN KEY (RideId) REFERENCES Ride (Id),
  CONSTRAINT FK_UserNote_UserLogin FOREIGN KEY (UserId) REFERENCES UserLogin (Id) ON DELETE CASCADE
);

CREATE TABLE UserPasswordReset (
  Id INT NOT NULL AUTO_INCREMENT,
  UserId INT NULL,
  ResetToken VARCHAR(255) NOT NULL,
  TokenExpiry DATETIME NOT NULL,
  IsUsed TINYINT(1) NOT NULL DEFAULT 0,
  Status VARCHAR(20) NULL,
  Created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserPasswordReset_UserLogin FOREIGN KEY (UserId) REFERENCES UserLogin (Id) ON DELETE CASCADE
);

CREATE TABLE UserPvg (
  Id INT NOT NULL AUTO_INCREMENT,
  UserId INT NULL,
  Resource VARCHAR(100) NOT NULL,
  CanRead TINYINT(1) NOT NULL DEFAULT 0,
  CanWrite TINYINT(1) NOT NULL DEFAULT 0,
  CanDelete TINYINT(1) NOT NULL DEFAULT 0,
  Created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserPvg_UserLogin FOREIGN KEY (UserId) REFERENCES UserLogin (Id) ON DELETE CASCADE
);

CREATE TABLE Visitor (
  Id INT NOT NULL AUTO_INCREMENT,
  SessionId CHAR(36) NULL,
  IpAddress VARCHAR(45) NOT NULL,
  DeviceType VARCHAR(50) NOT NULL,
  Browser VARCHAR(100) NULL,
  OperatingSystem VARCHAR(100) NULL,
  ReferrerUrl VARCHAR(500) NULL,
  PageVisited VARCHAR(500) NULL,
  VisitTimestamp DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  ExitTimestamp DATETIME NULL,
  Country VARCHAR(100) NULL,
  City VARCHAR(100) NULL,
  Region VARCHAR(100) NULL,
  PostalCode VARCHAR(20) NULL,
  Latitude DECIMAL(9, 6) NULL,
  Longitude DECIMAL(9, 6) NULL,
  DeviceInfo VARCHAR(500) NULL,
  UserAgent VARCHAR(500) NULL,
  LoginStatus TINYINT(1) NULL DEFAULT 0,
  UserId INT NULL,
  BookingAttempt TINYINT(1) NULL DEFAULT 0,
  RideId INT NULL,
  IsBot TINYINT(1) NULL DEFAULT 0,
  VisitedCounter INT NULL DEFAULT 1,
  MinutesSpent INT NULL DEFAULT 0,
  CreatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  DeletedFlag TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (Id),
  INDEX IDX_Visitor_IPAddress (IpAddress),
  INDEX IDX_Visitor_RideId (RideId),
  INDEX IDX_Visitor_UserId (UserId),
  INDEX IDX_Visitor_VisitTimestamp (VisitTimestamp)
);

CREATE VIEW vw_Drivervehicles AS
SELECT
  d.FirstName,
  d.LastName,
  dv.VehicleId,
  v.Make,
  v.Model,
  v.Seats
FROM Driver d
INNER JOIN DriverVehicle dv ON d.Id = dv.DriverId
INNER JOIN VehicleLK v ON dv.VehicleId = v.Id;
